# Generated by Django 3.0.7 on 2025-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('hardware_id', models.AutoField(primary_key=True, serialize=False)),
                ('hardware_name', models.CharField(max_length=255)),
                ('hardware_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Available', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
