# Generated by Django 3.0.7 on 2025-08-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_firmwareupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutableUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('file', models.FileField(upload_to=student_management_app.models.upload_executable_to, verbose_name='可执行文件')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '可执行文件上传',
                'verbose_name_plural': '可执行文件上传',
                'db_table': 'executable_uploads',
                'ordering': ['-upload_date'],
            },
        ),
    ]
